const createError = require('http-errors')

module.exports = {
  foo : async (req, res, next) => {
    try {
      
    } catch (error) {
      
    }
  }
}
